using CyreneJson.BuildTask.Helpers;
using Microsoft.CodeAnalysis;

namespace CyreneJson.BuildTask;

public class ContextEmitter(TypeCollector collector)
{
    private TypeCollector Collector { get; } = collector;

    public ContextEmitter Emit(string outDir)
    {
        EmitContext(outDir);
        EmitPolymorphic(outDir);
        return this;
    }

    private void EmitContext(string outDir)
    {
        var cb = new CodeBuilder();
        cb.AppendLine("// <auto-generated by CyreneJson/>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();
        cb.AppendLine("namespace CyreneJson;");
        cb.AppendLine();
        foreach (var key in Collector.AllTypes.Keys.Order())
            cb.AppendLine($"[global::System.Text.Json.Serialization.JsonSerializable(typeof({key}))]");
        cb.AppendLine("public partial class CyreneJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext { }");

        File.WriteAllText(Path.Combine(outDir, "CyreneJsonContext.g.cs"), cb.ToString());
    }

    private void EmitPolymorphic(string outDir)
    {
        foreach (var (key, info) in Collector.BaseTypes)
        {
            var baseType = info.BaseType;
            var derivedTypes = info.DerivedTypes;
            var ns = baseType.ContainingNamespace;
            if (derivedTypes.Count == 0) continue;

            var cb = new CodeBuilder();
            cb.AppendLine("// <auto-generated by CyreneJson/>");
            cb.AppendLine();
            if (ns != null && !ns.IsGlobalNamespace) cb.AppendLine($"namespace {ns.ToDisplayString()};");
            cb.AppendLine();
            cb.AppendLine("[global::System.Text.Json.Serialization.JsonPolymorphic(TypeDiscriminatorPropertyName = \"$type\")]");
            foreach (var derived in derivedTypes.OrderBy(d => d.Name))
                cb.AppendLine($"[global::System.Text.Json.Serialization.JsonDerivedType(typeof({TypeSymbolHelper.GetFullyQualifiedName(derived)}), \"{derived.Name}\")]");
            var access = baseType.DeclaredAccessibility switch
            {
                Accessibility.Internal => "internal",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.ProtectedAndInternal => "private protected",
                _ => "public"
            };
            var modifiers = baseType.IsAbstract ? "abstract " : baseType.IsSealed ? "sealed " : "";
            cb.AppendLine($"{access} {modifiers}partial class {baseType.Name} {{ }}");

            File.WriteAllText(Path.Combine(outDir, $"CyreneJson_{baseType.Name}.g.cs"), cb.ToString());
        }
    }
}
